apiVersion: v1
kind: Service
metadata:
  name: posts-cip-srv
spec:
  type: ClusterIP
  selector:
    app: posts # get all pods of labels app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
